### ISSUE TITLE
The performance of you implemence

### ISSUE THREAD

**Issue by zyxforever** [giakou4/MNIST_classification#1]
Thank you for sharing the codes,could you list the accuracy of the algorithms?

**Comment by giakou4** [comment]
I am updating with results soon.

**Comment by zyxforever** [comment]
Thank you very much, I run the SimCLR on cifar-10, the accuracy is higher than on Mnist. We know cifar-10 is much more "complex" than Mnist, is the characteristics of the SimCLR itself?

**Comment by giakou4** [comment]
SimCLR tends to create more robust representations. Conventional CNN lack robustness to out of distribution data or natural corruptions such as noise, blur and JPEG compression.
